# Generated by Django 5.2.5 on 2025-10-29 05:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_post12_delete_post11'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post12',
            new_name='Post13',
        ),
    ]
