# Generated by Django 5.2.5 on 2025-11-06 05:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profiles',
            new_name='profile',
        ),
    ]
