# Generated by Django 5.2.8 on 2025-12-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
