# Generated by Django 5.2.8 on 2025-12-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_remove_profile_profile_pic_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default/profile.png', upload_to='profile_pics/'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
    ]
