# Generated by Django 5.2.8 on 2025-12-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_follow_created_at_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
